Construct a Python document for the following example: A school purchases 2 computers from a shipment of 20 computers containing 3 defectives and 17 nondefectives. Try to obtain the values of the probability mass function, mean, and variance of the number of defective components purchased by the school.

 a. In the case you couldn't find out that the random variable has a hypergeometric distribution (with i. pure Python codes and ii. using SymPy FiniteRV), 

In [1]:
import numpy as np

In [33]:
#1ai. 

p_nondefective= 17/20
p_defective = 3/20
print('probability of non defective: ',p_nondefective,'\n', 'probability of defective: ',p_defective)
x = np.array([0, 1, 2])
def pmf(x):
    if x==0:
        return p_nondefective**2
    elif x ==1:
        return 2*p_defective * p_nondefective
    else:
        return p_defective**2




probability of non defective:  0.85 
 probability of defective:  0.15


In [35]:
for i in x:
    print(pmf(i))

0.7224999999999999
0.255
0.0225


In [36]:
for i in x:
    print(round(pmf(i),4))


0.7225
0.255
0.0225


In [37]:
pmf(2)

0.0225

In [38]:
sum(pmf(i) for i in x)


0.9999999999999999

In [39]:
for i in x:
    print(pmf(i)>=0)

True
True
True


In [40]:
pmf_X = np.array(list(pmf(i) for i in x))




In [41]:
pmf_X


array([0.7225, 0.255 , 0.0225])

In [42]:
#Expected values or the mean of x 
E_X = np.sum(x*pmf_X)
E_X


0.3

In [43]:
Var_X = np.sum(x**2*pmf_X) - (E_X)**2
Var_X

0.255

In [44]:
#1aii. 
from sympy.stats import FiniteRV, P, E, variance





In [45]:
sympy_pmf = {0: 0.7225, 1: 0.2550, 2: 0.0225}
X = FiniteRV('X', sympy_pmf)


In [46]:
P(X<1)


0.722500000000000

In [13]:
P(X<=1) - P(X<=0)


0.255000000000000

In [14]:
P(X<=2) - P(X<=1)



0.0225000000000000

In [15]:
# mean
E(X)


0.300000000000000

In [16]:
# Variance
variance(X)

0.255000000000000

b) In the case you found out that the random variable has a hypergeometric distribution but you don't know that the hypergeometric distribution is already defined in Python (with pure Python)

In [17]:
#1b. 
def factorial(x):
    if x == 0 or x == 1:
        return 1
    elif x<0:
        return "Factorial is not defined for negative numbers!"
    else:
        return x * factorial(x-1)

def nCx(n, x):
    return int(factorial(n) / (factorial(n-x)*factorial(x)))
pmf = [ ]
for i in x:
    pmf.append(nCx(2, i)* 0.15**i * (1 - 0.15)**(2 - i))
pmf



[0.7224999999999999, 0.255, 0.0225]

In [18]:
#for the mean

pmf_X = np.array(pmf)
pmf_X



array([0.7225, 0.255 , 0.0225])

In [19]:
E_X = 2*0.15
E_X



0.3

In [20]:
#for the variance

Var_X = 2*0.15*(1-0.15)
Var_X


0.255

c) In the case you found out that the random variable has a hypergeometric distribution and you know that the hypergeometric distribution is already defined in Python (using i. SymPy Hypergeometric and ii. SciPy Hypergeometric). 

In [21]:
#1ci. using sympy hypergeometric

from sympy.stats import Hypergeometric, density 



In [22]:
X = Hypergeometric('X', 20, 2, 3) 

k = density(X).dict
k


{0: 68/95, 1: 51/190, 2: 3/190}

In [23]:
#for the mean

E(X)


3/10

In [24]:
# for the variance

variance(X)



459/1900

In [25]:
#1cii. using Scipy hypergeometric
#M is the total number of computers, N is total number of defectives. The random variate n represents the number of defectives drawn without replacement from the total population

from scipy.stats import hypergeom
import scipy
[M, n, N] = [20, 2, 3]
rv = hypergeom(M, n, N)
x = np.arange(0, n+1)
pmf_dogs = rv.pmf(x)
pmf_dogs



array([0.71578947, 0.26842105, 0.01578947])

In [26]:
# mean 

mean= hypergeom.mean(M, n, N)
mean


0.30000000000000004

In [27]:
# variance

variance = hypergeom.var(M, n, N)
variance


0.24157894736842106

Construct a Python document for the following example: When a motorist stops at a red light at a certain intersection, the waiting time for the light to turn green (in seconds), is uniformly distributed on the interval (0, 30). Try to obtain some probabilities based on the waiting time of the motorist, mean, and variance of the waiting time.

a) Using SymPy ContinuousRV,

b) Using SymPy Uniform,

c) Using SciPy Uniform.

In [52]:
#a) Using SymPy ContinuousRV,

from sympy import Interval, cos
from sympy.stats import ContinuousRV
from sympy import Symbol



In [54]:
#mean 
mean = E(X)
mean


15.0000000000000

In [55]:
variance(X)


75.0000000000000

In [63]:
# Using sympy.stats.Uniform() method
from sympy.stats import Uniform, density

In [64]:
# Import sympy and Uniform
from sympy.stats import Uniform, density
from sympy import Symbol, pprint
  
z = 2
a = 0
b = 30
  
# Using sympy.stats.Uniform() method
X = Uniform("x", a, b)
gfg = density(X)(z)
  
pprint(gfg)

1/30


In [65]:
E(X)


15

In [66]:
variance(X)


75

In [67]:
# Using sympy.stats.Uniform() method
X = Uniform(x, 0, 30)
gfg = density(X)(x)
pprint(gfg)

⎧1/30  for X ≥ 0 ∧ X ≤ 30
⎨                        
⎩ 0        otherwise     


In [68]:
density(X)(2)

1/30

In [69]:
E(X)

15

In [70]:
variance(X)

75

In [ ]:
from scipy.stats import uniform

In [71]:
a, b = 0.0, 30.0
rv = uniform(a, b)
rv


In [72]:
R = uniform.rvs(a, b, size = 30)
R

array([ 5.93393013,  3.29279947, 28.57874193, 13.54505489, 20.86959491,
       23.91456927,  7.69084769, 25.52873999, 11.39964659, 10.78362483,
        0.49921781, 22.702463  , 23.29301604,  9.17180262, 21.47242619,
       23.38775192, 13.53415555, 16.28425715,  8.76672035,  8.30010395,
       20.62432691, 22.34698302, 27.28199146, 17.70697414, 27.90431485,
        7.94499366, 29.67604401, 23.80845875, 25.26471543,  9.66390854])

In [73]:
x = np.linspace(uniform.ppf(0.01, a, b), uniform.ppf(0.99, a, b), 30)
R = uniform.pdf(x, 0, 30)
R

array([0.03333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333,
       0.03333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333,
       0.03333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333,
       0.03333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333,
       0.03333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333,
       0.03333333, 0.03333333, 0.03333333, 0.03333333, 0.03333333])

In [74]:
E(X)

15

In [75]:
variance(X)

75